version: "3.8"

services:
  book-mysql:
    image: mysql:8.0
    container_name: book-mysql
    hostname: book-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=book-user
      - MYSQL_PASSWORD=book
    volumes:
      - mysql_data:/var/lib/mysql
      - share_data:/partage
    networks:
      - bigdata
    ports:
      - "8889:3306"

  dbt:
    build:
      context: .
      dockerfile: Dockerfile_DBT
    image: kader110591/dbt
    container_name: dbt
    hostname: dbt
    volumes:
      - dbt_data:/usr/app
      - share_data:/partage
    networks:
      - bigdata
    restart: always

  airflow:
    build:
      context: .
      dockerfile: Dockerfile_Airflow
    image: kader110591/airflow
    container_name: airflow
    hostname: airflow
    environment:
<<<<<<< HEAD
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: 'True'
=======
      AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Use LocalExecutor for simplicity in a single container
      AIRFLOW__CORE__AIRFLOW_CONFIG: /opt/airflow/config/airflow.cfg
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow  # Default, can be changed
      AIRFLOW__WEBSERVER__RBAC: 'True' # Enable RBAC for the UI
      # Add any other Airflow environment variables you need
>>>>>>> 65090f6b0f62d3bccf22ef894ceff110dee78cb5
    volumes:
      - airflow_dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - airflow_config:/opt/airflow/config
      - airflow_plugins:/opt/airflow/plugins
      - share_data:/partage
    ports:
      - "8080:8080"
    networks:
      - bigdata
    restart: always

  airflow-postgres:
    image: postgres:13-alpine
    container_name: airflow-postgres
    hostname: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
      - share_data:/partage
    ports:
      - "5432:5432"
    networks:
      - bigdata
    restart: always

volumes:
  airflow_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/airflow_volume/postgres_data
      o: bind

  airflow_dags:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/airflow_volume/dags
      o: bind

  airflow_logs:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/airflow_volume/logs
      o: bind

  airflow_plugins:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/airflow_volume/plugins
      o: bind

  airflow_config:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/airflow_volume/config
      o: bind

  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/mysql_volume
      o: bind

  dbt_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/dbt_volume
      o: bind

  share_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/kaderbalde/Documents/docker_volumes/partage_nifi/partage
      o: bind

networks:
  bigdata:
